ProyectoPAW/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoPAW.Controllers
{
    public class RoleController : Controller
    {
        [Authorize(Policy = "RequireProfesor")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        //[Authorize(Roles = "Administrador,Profesor")]
        public IActionResult Admin()
        {
            return View();
        }

        [Authorize(Policy = "RequireEstudiante")]
        public IActionResult Estudiante()
        {
            return View();
        }
    }
}

ProyectoPAW/Controllers/TcursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPAW.Areas.Identity.Data;
using ProyectoPAW.Models;

namespace ProyectoPAW.Controllers
{
    public class TcursoController : Controller
    {
        private readonly ProyectoWebAvanzadoContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TcursoController(ProyectoWebAvanzadoContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tcurso
        public async Task<IActionResult> Index()
        {
            var proyectoWebAvanzadoContext = _context.Tcursos.Include(t => t.Usuario);
            return View(await proyectoWebAvanzadoContext.ToListAsync());
        }

        // GET: Tcurso/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Tcursos == null)
            {
                return NotFound();
            }

            var tcurso = await _context.Tcursos
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tcurso == null)
            {
                return NotFound();
            }

            return View(tcurso);
        }

        // GET: Tcurso/Create
        public async Task<IActionResult> Create()
        {
            // Obtener la lista de usuarios con el rol de Profesor
            var profesores = await _userManager.GetUsersInRoleAsync("Profesor");

            // Crear una lista de SelectListItem para pasar a la vista
            var profesoresSelectList = profesores
                .Select(u => new SelectListItem { Value = u.Id, Text = $"{u.Nombre} {u.Apellidos}" })
                .ToList();

            ViewBag.UsuarioId = new SelectList(profesoresSelectList, "Value", "Text");
            return View();
        }




        // POST: Tcurso/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,Profesor,UsuarioId")] Tcurso tcurso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tcurso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            // Obtener la lista de usuarios con el rol de Profesor
            var profesores = await _userManager.GetUsersInRoleAsync("Profesor");

            // Crear una lista de SelectListItem para pasar a la vista
            var profesoresSelectList = profesores
                .Select(u => new SelectListItem { Value = u.Id, Text = $"{u.Nombre} {u.Apellidos}" })
                .ToList();

            ViewData["UsuarioId"] = new SelectList(profesoresSelectList, "Value", "Text");
            return View(tcurso);
        }

        // GET: Tcurso/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tcurso = await _context.Tcursos.FindAsync(id);
            if (tcurso == null)
            {
                return NotFound();
            }

            // Obtener la lista de usuarios con el rol de Profesor
            var profesores = await _userManager.GetUsersInRoleAsync("Profesor");

            // Crear una lista de SelectListItem para pasar a la vista
            var profesoresSelectList = profesores
                .Select(u => new SelectListItem { Value = u.Id, Text = $"{u.Nombre} {u.Apellidos}" })
                .ToList();

            ViewData["UsuarioId"] = new SelectList(profesoresSelectList, "Value", "Text", tcurso.UsuarioId);
            return View(tcurso);
        }

        // POST: Tcurso/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Nombre,Descripcion,Profesor,UsuarioId")] Tcurso tcurso)
        {
            if (id != tcurso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tcurso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TcursoExists(tcurso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var profesores = await _userManager.GetUsersInRoleAsync("Profesor");

            // Crear una lista de SelectListItem para pasar a la vista
            var profesoresSelectList = profesores
                .Select(u => new SelectListItem { Value = u.Id, Text = $"{u.Nombre} {u.Apellidos}" })
                .ToList();

            ViewData["UsuarioId"] = new SelectList(profesoresSelectList, "Value", "Text", tcurso.UsuarioId);
            return View(tcurso);
        }

        // GET: Tcurso/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Tcursos == null)
            {
                return NotFound();
            }

            var tcurso = await _context.Tcursos
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tcurso == null)
            {
                return NotFound();
            }

            return View(tcurso);
        }

        // POST: Tcurso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tcurso = await _context.Tcursos.FindAsync(id);
            if (tcurso == null)
            {
                return NotFound();
            }

            // Eliminar todas las relaciones TcursoRecetum relacionadas
            var relaciones = _context.TcursoReceta.Where(r => r.CursoId == id);
            _context.TcursoReceta.RemoveRange(relaciones);

            // Ahora elimina el curso
            _context.Tcursos.Remove(tcurso);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> CurosEstudiantes()
        {
            // Obtener el usuario actualmente autenticado
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            // Obtener los cursos en los que está matriculado el usuario actual
            var cursosDelUsuario = await _context.TcursoUsuarios
                .Where(cu => cu.UsuarioId == user.Id)
                .Select(cu => cu.Curso)
                .ToListAsync();

            return View(cursosDelUsuario);
        }


        public async Task<IActionResult> DetailsCurosEstudiantes(long? id)
        {
            if (id == null || _context.Tcursos == null)
            {
                return NotFound();
            }

            var tcurso = await _context.Tcursos
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tcurso == null)
            {
                return NotFound();
            }

            return View(tcurso);
        }

        public async Task<IActionResult> CursosProfesor()
        {
            var proyectoWebAvanzadoContext = _context.Tcursos.Include(t => t.Usuario);
            return View(await proyectoWebAvanzadoContext.ToListAsync());
        }

        private bool TcursoExists(long id)
        {
          return (_context.Tcursos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProyectoPAW/Controllers/TrecetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPAW.Areas.Identity.Data;
using ProyectoPAW.Models;

namespace ProyectoPAW.Controllers
{
    public class TrecetaController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ProyectoWebAvanzadoContext _context;

        public TrecetaController(UserManager<ApplicationUser> userManager, ProyectoWebAvanzadoContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Treceta
        public async Task<IActionResult> Index()
        {
            // Obtener los IDs de los usuarios con el rol de Profesor
            var profesores = await _userManager.GetUsersInRoleAsync("Profesor");

            // Obtener las recetas creadas por usuarios con el rol de Profesor
            var recetasDeProfesores = _context.Treceta
                .Include(t => t.Usuario)
                .ToList() // Convertir a lista para permitir la comparación en memoria
                .Where(r => profesores.Any(p => p.Id == r.UsuarioId));

            return View(recetasDeProfesores);
        }

        public async Task<IActionResult> MisRecetas()
        {
            var proyectoWebAvanzadoContext = _context.Treceta.Include(t => t.Usuario);
            return View(await proyectoWebAvanzadoContext.ToListAsync());
        }

        public async Task<IActionResult> RecetasProfesor()
        {
            var proyectoWebAvanzadoContext = _context.Treceta.Include(t => t.Usuario);
            return View(await proyectoWebAvanzadoContext.ToListAsync());
        }

        // GET: Treceta/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Treceta == null)
            {
                return NotFound();
            }

            var trecetum = await _context.Treceta
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trecetum == null)
            {
                return NotFound();
            }

            return View(trecetum);
        }

        // GET: Treceta/Create
        public IActionResult Create()
        {
            //ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Id");
            return View();
        }

        // POST: Treceta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UsuarioId,Nombre,Descripcion,Instrucciones,Categoria,Ingredientes")] Treceta trecetum)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                trecetum.UsuarioId = user.Id;

                _context.Add(trecetum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Id", trecetum.UsuarioId);
            return View(trecetum);
        }

        // GET: Treceta/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Treceta == null)
            {
                return NotFound();
            }

            var trecetum = await _context.Treceta.FindAsync(id);
            if (trecetum == null)
            {
                return NotFound();
            }
            ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Id", trecetum.UsuarioId);
            return View(trecetum);
        }

        // POST: Treceta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,UsuarioId,Nombre,Descripcion,Instrucciones,Categoria,Ingredientes")] Treceta trecetum)
        {
            if (id != trecetum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    trecetum.UsuarioId = user.Id;
                    _context.Update(trecetum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrecetumExists(trecetum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Id", trecetum.UsuarioId);
            return View(trecetum);
        }

        // GET: Treceta/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Treceta == null)
            {
                return NotFound();
            }

            var trecetum = await _context.Treceta
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trecetum == null)
            {
                return NotFound();
            }

            return View(trecetum);
        }

        // POST: Trecetas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var treceta = await _context.Treceta.FindAsync(id);
            if (treceta == null)
            {
                return NotFound();
            }

            // Eliminar todas las relaciones TcursoRecetum relacionadas
            var relaciones = _context.TcursoReceta.Where(r => r.RecetaId == id);
            _context.TcursoReceta.RemoveRange(relaciones);

            // Ahora elimina la receta
            _context.Treceta.Remove(treceta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool TrecetumExists(long id)
        {
          return (_context.Treceta?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProyectoPAW/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoPAW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoPAW.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoPAW</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
                            var roleOfUser = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value : "Estudiante";

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Admin">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Profesores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Estudiante">Estudiante</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tcurso" asp-action="Index">Curso</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Treceta" asp-action="Index">Receta</a>
                            </li>
                            
                            if (roleOfUser == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AspNetUsers" asp-action="Index">Usuarios</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProyectoPAW - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-area="" asp-controller="Home" asp-action="Nosotros">Nosotros</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoPAW/Views/Shared/_LayoutMain.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Escuela de cocina</title>
@*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoPAW.styles.css" asp-append-version="true" /> *@

    <link href="https://cdn.jsdelivr.net/npm/fastbootstrap@2.2.0/dist/css/fastbootstrap.min.css" rel="stylesheet" integrity="sha256-V6lu+OdYNKTKTsVFBuQsyIlDiRWiOmtC8VQ8Lzdm2i4=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoPAW</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
                            var roleOfUser = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value : "Estudiante";

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Admin">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Profesores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Estudiante">Estudiante</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tcurso" asp-action="Index">Curso</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Treceta" asp-action="Index">Receta</a>
                            </li>

                            if (roleOfUser == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AspNetUsers" asp-action="Index">Usuarios</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav> *@
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarButtonsExample"
                        aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img src="~/assets/images/logoCocina.png" width="36" />
                </a>
                <div class="collapse navbar-collapse" id="navbarButtonsExample">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
                            var roleOfUser = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value : "Estudiante";

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tcurso" asp-action="Index">Curso</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Treceta" asp-action="Index">Biblioteca de Recetas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Treceta" asp-action="MisRecetas">Mi Recetario</a>
                            </li>
                            if (roleOfUser == "Estudiante")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tcurso" asp-action="CurosEstudiantes">Mis Cursos</a>
                                </li>
                            }
                            if (roleOfUser == "Profesor")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tcurso" asp-action="CursosProfesor">Mis Cursos</a>
                                </li>
                            }
                            if (roleOfUser == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AspNetUsers" asp-action="Index">Usuarios</a>
                                </li>
                            }
                        }
                    </ul>
                    @* <div class="d-flex align-items-center ms-auto">
                        <a class="" id="login" asp-area="Identity" asp-page="/Account/Login">
                            <button type="button" class="btn btn-default px-3 me-2">
                                Iniciar Sesión
                            </button>
                        </a> *@
                    </div>
                    <partial name="_LoginPartial" />
                </div>
                        @* <button type="button" class="btn btn-primary me-3">
                            Registrarse
                        </button> *@
                        @* <a class="btn btn-subtle px-3"
                           href="https://github.com/mdbootstrap/mdb-ui-kit"
                           role="button">
                            <i class="fab fa-github"></i>
                        </a> *@
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Escuela de Cocina - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a> - <a asp-area="" asp-controller="Home" asp-action="Nosotros">Nosotros</a>
        </div>
    </footer> *@
@*     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>