ProyectoPAW/Models/Tcurso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ProyectoPAW.Models
{
    public partial class Tcurso
    {
        public Tcurso()
        {
            TcursoReceta = new HashSet<TcursoRecetum>();
            TcursoUsuarios = new HashSet<TcursoUsuario>();
        }

        public long Id { get; set; }

        [Required(ErrorMessage ="Este dato es requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Este dato es requerido")]
        [StringLength(200, ErrorMessage = "Los comentarios no pueden tener más de 200 caracteres.")]
        [DisplayName("Descripción")]
        public string Descripcion { get; set; }
        public string? CursoConProfesor
        {
            get
            {
                var profesor = TcursoUsuarios.FirstOrDefault()?.Usuario;
                return $"{Nombre} - Profesor: {profesor?.Nombre} {profesor?.Apellidos}";
            }
        }

        public string Profesor { get; set; }

        [Required(ErrorMessage = "Este dato es requerido")]
        [DisplayName("Profesor")]
        public string UsuarioId { get; set; }

        [DisplayName("Profesor")]
        public virtual AspNetUser? Usuario { get; set; } 
        public virtual ICollection<TcursoRecetum>? TcursoReceta { get; set; }
        public virtual ICollection<TcursoUsuario>? TcursoUsuarios { get; set; }
    }
}

ProyectoPAW/Controllers/TcursoRecetumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPAW.Areas.Identity.Data;
using ProyectoPAW.Models;

namespace ProyectoPAW.Controllers
{
    public class TcursoRecetumsController : Controller

    {
        private readonly ProyectoWebAvanzadoContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public TcursoRecetumsController(ProyectoWebAvanzadoContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TcursoRecetums
        public async Task<IActionResult> Index()
        {
            var proyectoWebAvanzadoContext = _context.TcursoReceta.Include(t => t.Curso).Include(t => t.Receta);
            return View(await proyectoWebAvanzadoContext.ToListAsync());
        }

        // GET: TcursoRecetums/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.TcursoReceta == null)
            {
                return NotFound();
            }

            var tcursoRecetum = await _context.TcursoReceta
                .Include(t => t.Curso)
                .Include(t => t.Receta)
                .FirstOrDefaultAsync(m => m.CursoId == id);
            if (tcursoRecetum == null)
            {
                return NotFound();
            }

            return View(tcursoRecetum);
        }

        // GET: TcursoRecetums/Create
        public async Task<IActionResult> Create()
        {
            // Obtener los IDs de los usuarios con el rol de Profesor
            var profesores = await _userManager.GetUsersInRoleAsync("Profesor");

            // Obtener las recetas creadas por usuarios con el rol de Profesor
            var recetasDeProfesores = _context.Treceta
                .AsEnumerable() // Convertir a enumerable para permitir la comparación en memoria
                .Where(r => profesores.Any(p => p.Id == r.UsuarioId))
                .ToList();

            // Crear una lista de SelectListItem para pasar a la vista
            var recetasSelectList = recetasDeProfesores
            .Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = $"{r.Nombre} - {profesores.FirstOrDefault(p => p.Id == r.UsuarioId)?.Nombre} {profesores.FirstOrDefault(p => p.Id == r.UsuarioId)?.Apellidos}"
            })
            .ToList();

            ViewData["Cursos"] = new SelectList(_context.Tcursos.Include(c => c.Usuario).ToList(), "Id", "CursoConProfesor");
            ViewData["Recetas"] = new SelectList(recetasSelectList, "Value", "Text");
            return View();
        }


        // POST: TcursoRecetums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CursoId,RecetaId")] TcursoRecetum tcursoRecetum)
        {
            
                _context.Add(tcursoRecetum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            ViewData["CursoId"] = new SelectList(_context.Tcursos, "Id", "Id", tcursoRecetum.CursoId);
            ViewData["RecetaId"] = new SelectList(_context.Treceta, "Id", "Id", tcursoRecetum.RecetaId);
            return View(tcursoRecetum);
        }

        // GET: TcursoRecetums/Edit/5


        // GET: TcursoRecetums/Edit/5
        public async Task<IActionResult> Edit(long? cursoId, long? recetaId)
        {
            if (cursoId == null || recetaId == null)
            {
                return NotFound();
            }

            var tcursoRecetum = await _context.TcursoReceta.FindAsync(cursoId, recetaId);
            if (tcursoRecetum == null)
            {
                return NotFound();
            }
            ViewData["CursoId"] = new SelectList(_context.Tcursos, "Id", "Id", tcursoRecetum.CursoId);
            ViewData["RecetaId"] = new SelectList(_context.Treceta, "Id", "Id", tcursoRecetum.RecetaId);
            return View(tcursoRecetum);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CursoId,RecetaId")] TcursoRecetum tcursoRecetum)
        {
            if (id != tcursoRecetum.CursoId)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(tcursoRecetum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TcursoRecetumExists(tcursoRecetum.CursoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
            ViewData["CursoId"] = new SelectList(_context.Tcursos, "Id", "Id", tcursoRecetum.CursoId);
            ViewData["RecetaId"] = new SelectList(_context.Treceta, "Id", "Id", tcursoRecetum.RecetaId);
            return View(tcursoRecetum);
        }

        // GET: TcursoRecetums/Delete/5
        // GET: TcursoRecetums/Delete
        public async Task<IActionResult> Delete(long? cursoId, long? recetaId)
        {
            if (cursoId == null || recetaId == null)
            {
                return NotFound();
            }

            var tcursoRecetum = await _context.TcursoReceta.FindAsync(cursoId, recetaId);
            if (tcursoRecetum == null)
            {
                return NotFound();
            }

            return View(tcursoRecetum);
        }

        // POST: TcursoRecetums/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long cursoId, long recetaId)
        {
            var tcursoRecetum = await _context.TcursoReceta.FindAsync(cursoId, recetaId);
            if (tcursoRecetum == null)
            {
                return NotFound();
            }

            _context.TcursoReceta.Remove(tcursoRecetum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        private bool TcursoRecetumExists(long id)
        {
            return (_context.TcursoReceta?.Any(e => e.CursoId == id)).GetValueOrDefault();
        }
    }
}

ProyectoPAW/Controllers/TcursoUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoPAW.Models;

namespace ProyectoPAW.Controllers
{
    public class TcursoUsuariosController : Controller
    {
        private readonly ProyectoWebAvanzadoContext _context;

        public TcursoUsuariosController(ProyectoWebAvanzadoContext context)
        {
            _context = context;
        }

        // GET: TcursoUsuarios
        public async Task<IActionResult> Index()
        {
            var proyectoWebAvanzadoContext = _context.TcursoUsuarios.Include(t => t.Curso).Include(t => t.Usuario);
            return View(await proyectoWebAvanzadoContext.ToListAsync());
        }

        // GET: TcursoUsuarios/Details/5
        public async Task<IActionResult> Details(long? cursoId, long? usuarioID )
        {
            if (cursoId == null || _context.TcursoUsuarios == null)
            {
                return NotFound();
            }

            var tcursoUsuario = await _context.TcursoUsuarios
                .Include(t => t.Curso)
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.CursoId == cursoId);
            if (tcursoUsuario == null)
            {
                return NotFound();
            }

            return View(tcursoUsuario);
        }

        // GET: TcursoUsuarios/Create
        public IActionResult Create()
        {
            ViewData["CursoId"] = new SelectList(_context.Tcursos.Include(c => c.Usuario), "Id", "CursoConProfesor");
            ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Nombre");
            return View();
        }

        // POST: TcursoUsuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CursoId,UsuarioId")] TcursoUsuario tcursoUsuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tcursoUsuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CursoId"] = new SelectList(_context.Tcursos, "Id", "CursoConProfesor", tcursoUsuario.CursoId);
            ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "NombreCompleto", tcursoUsuario.UsuarioId);
            return View(tcursoUsuario);
        }

        // GET: TcursoUsuarios/Matricula
        public IActionResult Matricula()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // Obtener el ID del usuario logueado
            var cursos = _context.Tcursos.ToList();
            ViewData["CursoId"] = new SelectList(cursos, "Id", "Nombre");
            ViewData["UsuarioId"] = userId; // Establecer el ID de usuario en la vista
            return View();
        }

        // POST: TcursoUsuarios/Matricula
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Matricula([Bind("CursoId,UsuarioId")] TcursoUsuario tcursoUsuario)
        {
            // Obtener el ID del usuario logueado
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Verificar si el usuario ya está matriculado en el curso
            var existingMatricula = await _context.TcursoUsuarios
                .FirstOrDefaultAsync(m => m.CursoId == tcursoUsuario.CursoId && m.UsuarioId == userId);

            if (existingMatricula != null)
            {
                // El usuario ya está matriculado en el curso, redirigir a Index
                return RedirectToAction("Index", "Tcurso");
            }

            // Asignar el ID de usuario al modelo TcursoUsuario
            tcursoUsuario.UsuarioId = userId;

            _context.Add(tcursoUsuario);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Tcurso");
        }



        // GET: TcursoUsuarios/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.TcursoUsuarios == null)
            {
                return NotFound();
            }

            var tcursoUsuario = await _context.TcursoUsuarios.FindAsync(id);
            if (tcursoUsuario == null)
            {
                return NotFound();
            }
            ViewData["CursoId"] = new SelectList(_context.Tcursos, "Id", "Id", tcursoUsuario.CursoId);
            ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Id", tcursoUsuario.UsuarioId);
            return View(tcursoUsuario);
        }

        // POST: TcursoUsuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,CursoId,UsuarioId")] TcursoUsuario tcursoUsuario)
        {
            if (id != tcursoUsuario.CursoId)
            {
                return NotFound();
            }

            
                try
                {
                    _context.Update(tcursoUsuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TcursoUsuarioExists(tcursoUsuario.CursoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
            ViewData["CursoId"] = new SelectList(_context.Tcursos, "Id", "Id", tcursoUsuario.CursoId);
            ViewData["UsuarioId"] = new SelectList(_context.AspNetUsers, "Id", "Id", tcursoUsuario.UsuarioId);
            return View(tcursoUsuario);
        }

        // GET: TcursoUsuarios/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.TcursoUsuarios == null)
            {
                return NotFound();
            }

            var tcursoUsuario = await _context.TcursoUsuarios
                .Include(t => t.Curso)
                .Include(t => t.Usuario)
                .FirstOrDefaultAsync(m => m.CursoId == id);
            if (tcursoUsuario == null)
            {
                return NotFound();
            }

            return View(tcursoUsuario);
        }

        // POST: TcursoUsuarios/Delete/5


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long cursoId, string usuarioId)
        {
            var tcursoUsuario = await _context.TcursoUsuarios.FirstOrDefaultAsync(m => m.CursoId == cursoId && m.UsuarioId == usuarioId);
            if (tcursoUsuario == null)
            {
                return NotFound();
            }

            _context.TcursoUsuarios.Remove(tcursoUsuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: TcursoUsuarios/QuitarMatricula
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> QuitarMatricula(long cursoId, string usuarioId)
        {
            var tcursoUsuario = await _context.TcursoUsuarios.FirstOrDefaultAsync(m => m.CursoId == cursoId && m.UsuarioId == usuarioId);
            if (tcursoUsuario == null)
            {
                return NotFound();
            }

            _context.TcursoUsuarios.Remove(tcursoUsuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool TcursoUsuarioExists(long id)
        {
          return (_context.TcursoUsuarios?.Any(e => e.CursoId == id)).GetValueOrDefault();
        }
    }
}

ProyectoPAW/Views/Tcurso/Create.cshtml
@model ProyectoPAW.Models.Tcurso
@using System.Security.Claims

@{
    ViewData["Title"] = "Nuevo Curso";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}
<br />
<h1>Nuevo Curso</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>

            <input asp-for="Profesor" class="form-control" type="hidden" value="No procede" />
            
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <select asp-for="UsuarioId" class="form-control" asp-items="ViewBag.UsuarioId"></select>
            </div>

            <br />
            <div class="form-group">
                <a asp-action="Index" class="btn btn-default px-3 me-2">Volver</a>
                <input type="submit" value="Guardar" class="btn" style="background-color: #9c3840; color: white;">
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoPAW/Views/Tcurso/CurosEstudiantes.cshtml
@model IEnumerable<ProyectoPAW.Models.Tcurso>

@{
    
    ViewData["Title"] = "Mis Cursos";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h1>Mis Cursos</h1>
<hr />

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card">
                <a asp-action="Details" asp-route-id="@item.Id"><img src="~/assets/images/placeholderCurso.png" class="card-img-top" alt="card example" /></a>
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Nombre)</h5>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Descripcion)</p>
                    <div class="text-center">
                        <a asp-action="DetailsCurosEstudiantes" asp-route-id="@item.Id" class="btn btn-default">Ver Detalles</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ProyectoPAW/Views/Tcurso/CursosProfesor.cshtml
@using ProyectoPAW.Services
@model IEnumerable<ProyectoPAW.Models.Tcurso>
@inject ICantidadRecetas cantidadRecetas
@inject ICantidadUsuarios cantidadUsuarios
@using System.Security.Claims
@{
    ViewData["Title"] = "Cursos";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";

    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var numeroCursos = Model.Count(r => r.UsuarioId == userId);
}

<h1>Mis Cursos (@numeroCursos)</h1>


@if (numeroCursos > 0)
{
    <p>
        <a asp-action="Create" class="btn" style="background-color: #9c3840; color: white;">Nuevo Curso</a>
    </p>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var item in Model.Where(r => r.UsuarioId == userId))
        {
            <div class="col">
                <div class="card">
                    <a asp-action="Details" asp-route-id="@item.Id"><img src="~/assets/images/placeholderCurso.png" class="card-img-top" alt="card example" /></a>
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Nombre)</h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Descripcion)</p>
                        <p>La cantidad de Recetas agregadas son: @cantidadRecetas.ObtenerCantidadRecetas((int)item.Id)</p>
                        <p>La cantidad de Usuarios registados son: @cantidadUsuarios.ObtenerCantidadUsuarios((int)item.Id)</p>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default px-3 me-2">Editar</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-default px-3 me-2">Ver</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default px-3 me-2">Eliminar</a>
                        


                    </div>
                </div>
            </div>
        }
    </div>

}
else
{
    <br />
    <br />
    <br />
    <div class="text-center">
        <h2>No hay cursos asignados</h2>
        <p>¡Despierta tu creatividad y comienza a diseñar tus fascinantes lecciones!</p>
        <br />
        <div class="d-grid gap-2 col-2 mx-auto">
            <a asp-action="Create" class="btn" style="background-color: #9c3840; color: white;">Nuevo Curso</a>
        </div>
    </div>
    <br />
    <br />
    <br />
}

ProyectoPAW/Views/Tcurso/Delete.cshtml
@model ProyectoPAW.Models.Tcurso

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tcurso</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Nombre) @Html.DisplayFor(model => model.Usuario.Apellidos)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProyectoPAW/Views/Tcurso/Details.cshtml
@model ProyectoPAW.Models.Tcurso
@using System.Security.Claims

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h1>Detalles del Curso</h1>
<hr />
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsuarioId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Nombre) @Html.DisplayFor(model => model.Usuario.Apellidos)
        </dd>
    </dl>
</div>
<br />
<div class="text-center">
    @if (User.IsInRole("Profesor") || User.IsInRole("Administrador"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-default px-3 me-2">Modificar</a>
    }
    <a asp-action="Index" class="btn btn-default px-3 me-2">Volver</a>
</div>

ProyectoPAW/Views/Tcurso/DetailsCurosEstudiantes.cshtml
@model ProyectoPAW.Models.Tcurso

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h1>Detalles del Curso</h1>
<hr />
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UsuarioId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Nombre) @Html.DisplayFor(model => model.Usuario.Apellidos)
        </dd>
    </dl>
</div>
<br />
<div class="text-center">
    <a asp-action="CurosEstudiantes" class="btn btn-default px-3 me-2">Volver a Mis Cursos</a>
</div>

ProyectoPAW/Views/Tcurso/Index.cshtml
@using ProyectoPAW.Services
@using System.Security.Claims

@model IEnumerable<ProyectoPAW.Models.Tcurso>
@inject ICantidadRecetas cantidadRecetas
@inject ICantidadUsuarios cantidadUsuarios
@{
    ViewData["Title"] = "Cursos";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h1>Cursos</h1>
@if (User.Identity.IsAuthenticated)
{
    var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
    var roleOfUser = claimsIdentity != null ? claimsIdentity.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value : "Estudiante";

    if (roleOfUser == "Estudiante")
    {
        <p>
            <a asp-controller="TcursoUsuarios" asp-action="Matricula" class="btn" style="background-color: #9c3840; color: white;">Matricular Curso</a>
        </p>
    }

    if (roleOfUser == "Profesor" || roleOfUser == "Administrador")
    {
        <br />
        <div>
            <a asp-action="Create" class="btn" style="background-color: #9c3840; color: white;">Nuevo Curso</a>


            <a asp-area="" asp-controller="TcursoRecetums" asp-action="Index" class="btn" style="background-color: #9c3840; color: white;">Agregar recetas</a>

            <a asp-area="" asp-controller="TcursoUsuarios" asp-action="Index" class="btn" style="background-color: #9c3840; color: white;">Agregar estudiantes</a>
        </div>
        <br />
    }
}

<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in Model)
    {
        var matriculado = cantidadUsuarios.ObtenerCantidadUsuarios((int)item.Id) > 0;
        <div class="col">
            <div class="card">
                <a asp-action="Details" asp-route-id="@item.Id"><img src="~/assets/images/placeholderCurso.png" class="card-img-top" alt="card example" /></a>
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Nombre)</h5>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Descripcion)</p>
                    <p>Recetas agregadas son: @cantidadRecetas.ObtenerCantidadRecetas((int)item.Id)</p>
                    <p>Estudiantes matriculados: @cantidadUsuarios.ObtenerCantidadUsuarios((int)item.Id)</p>
                    @* @if (User.IsInRole("Estudiante") && matriculado)
                    {
                        <p class="fw-bold">¡Ya estás matriculado en este curso!</p>
                    } *@
                    @if (User.IsInRole("Profesor") || User.IsInRole("Administrador"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default px-3 me-2">Editar</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-default px-3 me-2">Ver</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default px-3 me-2">Eliminar</a>
                    }

            
                </div>
            </div>
        </div>
    }
</div>